main:
  - identifier: about
    name: About                              
    url: /about                              
    weight: 100                              
  - identifier: contact
    name: Contact Us
    url: /contact                            
    weight: 200
  - identifier: blog
    name: Blog
    url: /blog
  - identifier: news
    name: News
    url: /news
