  color: "#4f46e5" 
  copyright: "Copyright &copy; 2023 Digital Elasticity. All Rights Reserved." 
  footer: 
    - title: About 
      content:  > 
        Acme Corporation is the world's leading 
        manufacturer of digital shapes. From squares and 
        circles to triangles and hexagons, we have it 
        all. Browse through our collection of various 
        forms with different thicknesses and line styles. 
        You live in the world. We shape it. 
  
  
    - title: Recent Blog Posts 
      recents: blog 
      recentCount: 7 
    - title: Contact Us 
      contact: true 
      